export default{
    products: [
      {
        _id: '1',
        image: '/images/sudadera-gris.jpg',
        name: 'Harry Potter Sweatshirt',
        brand: 'Mundo Harry Potter',
        price: 4.37,
        stars: 6.1,
        reviews: 21,
        color: 'Gray', 
      },
      {
        _id: '2',
        image:'/images/sudadera-negra-pink.jpg',
        name: "Victoria's Secret Sweatshirt",
        brand: "PINK - Victoria's Secret",
        price: 46.95,
        stars: 7.0,
        reviews: 35,
        color: 'Black', 
        
      },
      {
        _id: '3',
        image:'/images/sudadera-rosa.jpg',
        name: 'Pink Sweatshirt',
        brand: 'Harajuku',
        price: 25.04,
        stars: 2.1,
        reviews: 12,
        color: 'Pink', 
      }, 
      {
        _id: '4',
        image: '/images/sudadera-blanca-gap.jpg',
        name: 'GAP WHITE FLAG USA',
        brand: 'GAP',
        price: 48.25 ,
        stars: 6.8,
        reviews: 23,
        color: 'White', 
      },
      {
        _id: '5',
        image:'/images/sudadera-gris-adidas.jpg',
        name: 'Adidas Originals',
        brand: 'Adidas',
        price: 57.33,
        stars: 7.1,
        reviews: 15,
        color: 'Gray', 
      },
      {
        _id: '6',
        image:'/images/sudadera-negra-aeropostale.jpg',
        name: 'Black Aéropostale Sweatshirt',
        brand: 'Aéropostale',
        price: 35.95,
        stars: 4.1,
        reviews: 22,
        color: 'Black', 
      },
      {
        _id: '7',
        image:'/images/sudadera-blanca.jpg',
        name: 'White Sweatshirt',
        brand: 'Tommy Hilfiger',
        price: 52.59,
        stars: 5.5,
        reviews: 13,
        color: 'White', 
      },
      {
        _id: '8',
        image:'/images/sudadera-negra-mula.jpg',
        name: 'Casual Sweatshirt',
        brand: 'Mula',
        price: 16.33,
        stars: 9.1,
        reviews: 18,
        color: 'Black', 
      }
    ]
  }